### ISSUE TITLE
Fatal error when using shortcode

### ISSUE THREAD

**Issue by chrisaldrich** [kshaffer/hypothesis_aggregator#4]
Old posts which have the aggregator's short code in them now throw a fatal error. (eg: http://boffosocko.com/2016/06/18/a-new-thermodynamics-theory-of-the-origin-of-life-quanta-magazine/) 

Removing the short code from the post causes the error to resolve.

I suspect that it may be as a result of the recent upgrade to WordPress 4.7, but the error notice pasted below may prove additional details.

Has anyone else encountered this?

`Fatal error: Uncaught Error: Call to undefined function split() in /wp-content/plugins/hypothesis_aggregator-master/hypothesis-aggregator.php:140 Stack trace: #0 /wp-includes/shortcodes.php(345): hypothesis_shortcode(Array, '', 'hypothesis') #1 [internal function]: do_shortcode_tag(Array) #2 /wp-includes/shortcodes.php(223): preg_replace_callback('/\\[(\\[?)(hypoth...', 'do_shortcode_ta...', '<p>References:<...') #3 /wp-includes/class-wp-hook.php(298): do_shortcode('<p>References:<...') #4 /wp-includes/plugin.php(203): WP_Hook->apply_filters('<p>References:<...', Array) #5 /wp-includes/post-template.php(240): apply_filters('the_content', 'References:\n\n<u...') #6 /wp-content/themes/twentysixteen/template-parts/content-single.php(22): the_c in /wp-content/plugins/hypothesis_aggregator-master/hypothesis-aggregator.php on line 140`

**Comment by xolotl** [comment]
I think this is due to PHP7 incompatibility with PHP split(). I think I addressed it with now merged: https://github.com/kshaffer/hypothesis_aggregator/pull/6/commits/aa16da1421942c7a0bd5ce39b9054f960f65eec5

**Comment by xolotl** [comment]
Actually, on closer examination, I needed to adjust the fix I mentioned above and have done so with this PR: https://github.com/kshaffer/hypothesis_aggregator/pull/7

**Comment by chrisaldrich** [comment]
<a href="https://github.com/kshaffer/hypothesis_aggregator/issues/4" class="u-in-reply-to"></a>Sadly, I hadn't thought to check the PHP version, though mostly because my host apparently did a forced upgrade to 7.

You've just updated with another PR as I'm writing this. Does the new one fix the Currated by _____ piece? The intermediate code wasn't returning the user name or the correct URL for that user?

**Comment by chrisaldrich** [comment]
<a href="https://github.com/kshaffer/hypothesis_aggregator/issues/4" class="u-in-reply-to"></a>Yes, that tweak (https://github.com/kshaffer/hypothesis_aggregator/pull/7) does appear to work. It fixes both the fatal error and the fact that the curator name and appropriate URL wasn't working.

Great "marketing" work @xolotl! ;)

**Comment by xolotl** [comment]
Yes, the fixes I contributed are designed to address PHP7 compatibility, make the links to annotations include the annotation client by proxy in case someone doesn't have the extension, and fix the link to the curator that I broke in an earlier fix ;)

The "new face" of marketing apparently includes some facility with code ;)
